baseURL: "https://leovan.tech/"
enableEmoji: true
hasCJKLanguage: true
ignoreFiles:
  - \.Rmarkdown$
  - \.Rmd$"
  - \.knit\.md$
  - \.utf8\.md$
  - _files$
  - _cache$
  - \.txt$
  - \.csv$
  - \.tsv$
  - \.tgz$
  - \.tar$
  - \.gz$
  - \.zip$
  - \.npz$
languageCode: "zh-cn"
title: "范叶亮的技术小站 | Leo Van's Technical Website"
rssLimit: 100

services:
  googleAnalytics:
    ID: "G-8VPQF5ZTVD"

disableKinds:
  - "taxonomy"
  - "term"

permalinks:
  open-source: "/open-source/:slug/"

menu:
  main:
    - name: "开源项目"
      url: "/open-source/"
      weight: 1
    - name: "关于"
      url: "/about/"
      weight: 2

params:
  title: "范叶亮的技术小站"
  subtitle: "Leo Van's Technical Website"
  author: "范叶亮 | Leo Van"
  description: "范叶亮的技术小站 | Leo Van's Technical Website"
  logo: "/images/web/avatar-light-theme.svg"
  logoWidth: 150
  footer: "Copyright &copy; 2017-{Year} [范叶亮 | Leo Van](https://leovan.me)"
  licenseURL: "https://github.com/leovan/leovan.tech/blob/main/LICENSE"
  googleAdsense: "ca-pub-2608165017777396"
  indexSections:
    - "open-source"

  socialIcons:
    - title: "个人主页"
      icon: "/images/icons/house.svg"
      url: "https://leovan.me"
    - title: "Github"
      icon: "/images/icons/github.svg"
      url: "https://github.com/leovan/"
    - title: "RSS"
      icon: "/images/icons/rss.svg"
      url: "/rss/"

  clipboardjsVersion: "2.0.11"
  lazysizesVersion: "5.3.2"
  mathjaxVersion: "3.2.2"
  jsCookieVersion: "3.0.5"
  vanillaBackToTopVersion: "latest"

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1
